### ISSUE TITLE
Feature Tests

### ISSUE THREAD

**Issue by markwylde** [puzed/puzed-api#7]
There are currently some tests, but due to the close integration with github, testing became too intense, having to mock out github's apis.

Once the Membership and Source Providers have been implemented, the code's third party dependencies should be less coupled.

Features tests should be added for all core functionality and providers.

**Comment by KoryNunn** [comment]
Tests for at least happy cases of existing functionality would be great and would assist other developers

**Comment by markwylde** [comment]
The foundation of feature tests have now been implemented, and feature testing will now be an ongoing effort.
